#!/bin/bash
mvn install

# java -jar generator/generator.jar -k grid -h 1080 -w 1920 -p 1000 -s 20 -o img/grid.mesh
java -jar generator/generator.jar -k irregular -h 1080 -w 1920 -p 1000 -s 20 -o img/irregular.mesh

# ISLAND
# java -jar island/island.jar -i input.mesh -o lagoon.mesh --mode lagoon

java -jar island/island.jar

# java -jar visualizer/visualizer.jar -i img/grid.mesh -o img/grid.svg
# java -jar visualizer/visualizer.jar -i img/grid.mesh -o img/grid_debug.svg -x
# java -jar visualizer/visualizer.jar -i img/irregular.mesh -o img/irregular.svg   
java -jar visualizer/visualizer.jar -i img/lagoon.mesh -o img/irregular_debug.svg